apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: defeated-bass-go 
  janus-idp.io/tekton: defeated-bass-go
  backstage.io/kubernetes-id: defeated-bass-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: defeated-bass-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  