apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: defeated-bass-go-gitops
  description: This is GitOps manifest for defeated-bass-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: defeated-bass-go
    janus-idp.io/tekton: defeated-bass-go 
    backstage.io/kubernetes-id: defeated-bass-go 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:defeated-bass-go
