apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: defeated-bass-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:9442851d5ec49edefd83bce95a315b0e8d31bcbf@sha256:cf2ec7b42bbdf62d23fec22bc2cc25b089465ffcf4318c14ad8f332731d3b4e3
          name: container-image
